import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Layout/Header";
import Navbar from "./Layout/Navbar";
import Footer from "./Layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen overflow-x-hidden">
        <Header/>
        <div className="flex">
          <Navbar/>
          <main className="w-full">{children}</main>
        </div>
        <Footer/> 
      </body>
    </html>
  );
}
